#!/bin/bash
echo "Script for RBGS"
echo "set your login name: "
read loginname
#ssh $loginname@i10hpc.informatik.uni-erlangen.de
#qsub -I -l nodes=1:ppn=32:compute -l walltime=01:00:00


grids=(32 33 1024 1025 2048 2049)
cores=(1 2 4 8 16 32)
tasks=36
current_task=0
number_iterations=500
#echo "number of iterations(default 500): "

#read number_iterations

for dim in "${grids[@]}"
do
for threads in "${cores[@]}"
do
echo "**************************************"
echo "culcalating with grid size" $dim

export OMP_NUM_THREADS=$threads
echo "number of threads" $OMP_NUM_THREADS

./rbgs $dim $dim $number_iterations -log
current_task=$(($current_task + 1))

echo "task $current_task of $tasks completed"
	
done
done
